name: "universc"
description: Module to run UniverSC an open-source pipeline to demultiplex and process single-cell RNA-Seq data
keywords:
  - demultiplex
  - align
  - single-cell
  - scRNA-Seq
  - count
  - umi
tools:
  - "universc":
      ## TODO nf-core: Add a description and other details for the software below
      description: "UniverSC: a flexible cross-platform single-cell data processing pipeline"
      homepage: "https://hub.docker.com/r/tomkellygenetics/universc"
      documentation: "https://raw.githubusercontent.com/minoda-lab/universc/master/man/launch_universc.sh"
      tool_dev_url: "https://github.com/minoda-lab/universc"
      doi: "https://doi.org/10.1101/2021.01.19.427209"
      licence: ["GPL-3.0-or-later"]

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  ## TODO nf-core: Delete / customise this example input
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software version
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

authors:
  - "@kbattenb"
